### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by yurilavinas** [PyQuake/earthquakemodels#1]
# TODO list

- [] Conferir que o 'mean' do código é  a mesma do paper e que o está correto.

- [ ] Send/recv não funciona no mac. Conferir com computadores do laboratório.

**Comment by caranha** [comment]
Yuri, quanto ao send/recv, construa um teste (um programa pequeno que simplesmente executa a instrucao necessaria no codigo com os parametros mais basicos possiveis) para facilitar a sua verificacao.

**Comment by caranha** [comment]
Alias, estes dois pontos que voce colocou sao problemas bem diferentes. Eu sugiro que voce feche esta issue e abra duas, uma para cada um dos pontos acima.

**Comment by caranha** [comment]
Quebrei esta issue nas issues #2 e #3
